### ISSUE TITLE
Nice APP with some bugs

### ISSUE THREAD

**Issue by DerBaliner** [kaii-lb/LavenderPhotos#1]
Nice APP with some bugs

1. in albums folder screenshot is not displayed 
2. the folder for the lock does not work 
3. the trash folder does not work
4. under settings the data & backup and settings button have no function
5. under about and updates the updates and support & donate button has no function 

Strange, the screenshots are displayed in the search, you can view them and switch to the next one 

Please add that you can create your own folders and delete the Whatsapp and Instagram folder

And maybe a button to take a photo, like in fossify gallery

**Comment by kaii-lb** [comment]
fixed the not being able to remove whatsapp and instagram folders.
btw you can remove any album by entering it and clicking the settings icon -> remove album

**Comment by DerBaliner** [comment]
### fixed the not being able to remove whatsapp and instagram folders.
btw you can remove any album by entering it and clicking the settings icon -> remove album### 

Unfortunately this does not work, if I delete the WhatsApp and Instagram folders, they are no longer displayed, but if I then close the app and open it again, they are displayed again 🤔
![Screenshot_20241128-181848_Photos](https://github.com/user-attachments/assets/179d01ad-0ad5-4ef7-bfdc-3b3c00db1abf)
![Screenshot_20241128-181914_Photos](https://github.com/user-attachments/assets/d89b07c1-15ed-47d4-b25b-dfb871b4225c)

**Comment by kaii-lb** [comment]
> At the pic's you can see it, I have trashed both pic's in MiXplorer and don't shown in your App

mixplorer doesn't seem to trash stuff in the default android way, so it won't show but. but if you use any app that does use content resolver for its trash function then they'll show up in lavender photos too (one i know works is google photos)

> in albums folder screenshot is not displayed

can you get a log of that? i can't see a reason why that would be failing (esp since the album preview image is correct)

**Comment by rafnov** [comment]
I got #1 and #3 too.
![Screenshot_2024-12-03-08-56-17-17_129607156278eeca4540f58e8f742bdf.jpg](https://github.com/user-attachments/assets/496f2a5c-18b7-4fdb-ae49-e57005cfef86)

![Screenshot_2024-12-03-08-56-04-17_129607156278eeca4540f58e8f742bdf.jpg](https://github.com/user-attachments/assets/eac8c9d4-d986-4e3f-ad9f-1af1720feedd)

**Comment by DerBaliner** [comment]
> mixplorer doesn't seem to trash stuff in the default android way, so it won't show but. but if you use any app that does use content resolver for its trash function then they'll show up in lavender photos too (one i know works is google photos)

But MiXplorer deletes, either to the recycle bin or permanently

> can you get a log of that? i can't see a reason why that would be failing (esp since the album preview image is correct) edit: try adding the screenshot folder on your own from the setting icon, does that work?

How can I provide you with logs?

It works to create the screenshots folder, then 2 screenshots folders are displayed and if you delete the old one, both are gone

**Comment by kaii-lb** [comment]
> But MiXplorer deletes, either to the recycle bin or permanently

yes, but to its own recycle bin it seems not the "android recycle bin" so to speak. I cannot include recycle bin compatibility for every app, so only apps that use android's content resolver to delete or trash stuff will work.

> How can I provide you with logs?
run `adb logcat --pid=$(adb shell pidof com.kaii.photos) > log.txt' on a computer connected to the phone via usb debugging after starting the app, then do whatever causes the issue. send that log.txt file :D

**Comment by DerBaliner** [comment]
> yes, but to its own recycle bin it seems not the "android recycle bin" so to speak. I cannot include recycle bin compatibility for every app, so only apps that use android's content resolver to delete or trash stuff will work.

OK, no problem, I didn't know that there are several trashes 😂

> run `adb logcat --pid=$(adb shell pidof com.kaii.photos) > log.txt' on a computer connected to the phone via usb debugging after starting the app, then do whatever causes the issue. send that log.txt file :D

I will send soon 😉

**Comment by DerBaliner** [comment]
Here the logs 😉
[2024-12-07-11-40-46.txt](https://github.com/user-attachments/files/18049190/2024-12-07-11-40-46.txt)

**Comment by kaii-lb** [comment]
so theres only one case in which that would show up, and the log for it isn't shown in the log you sent. interesting for sure, i'll make a debug build and link it here

**Comment by DerBaliner** [comment]
> so theres only one case in which that would show up, and the log for it isn't shown in the log you sent. interesting for sure, i'll make a debug build and link it here
> 
> edit: [here's the link](https://drive.google.com/file/d/1CnVnTNK1vt4Kl82unswJduN4omWPCRFc/view?usp=sharing) edit #2: the log file is present in internal storage/LavenderPhotos, no need for adb

New debug log
[log.txt](https://github.com/user-attachments/files/18136611/log.txt)

**Comment by kaii-lb** [comment]
ohhh i see what the issue might be, i'll try to fix it when possible, thanks for the log!

**Comment by DerBaliner** [comment]
> ohhh i see what the issue might be, i'll try to fix it when possible, thanks for the log!

Gladly, I hope you can fix it with this 😉 👍

**Comment by DerBaliner** [comment]
Here are new logs
[log.txt](https://github.com/user-attachments/files/18212005/log.txt)

Something is strange, your updated app is supposed to be 0.84, but when I install the app and check the version in Droid-ify or MiXplorer, it says 0.8.3 beta 83 🤔🤷‍♂️
![Screenshot_20241220-155202_Droid-ify](https://github.com/user-attachments/assets/0ec651d0-e489-4d5f-9ee7-a5c533843f9d)
![Screenshot_20241220-153856_MiXplorer](https://github.com/user-attachments/assets/2d9ff55f-3e20-4f6c-8c3d-c6d40fed3a3b)
![Screenshot_20241220-154934_Photos](https://github.com/user-attachments/assets/5120fe78-fce6-4fbe-b38b-d05109542342)
The latest 0.8.4 is displayed as installed in Obtainium
![Screenshot_20241220-155544_Obtainium](https://github.com/user-attachments/assets/eff4f47e-be40-4f48-85e9-68d40ba373a1)

When I want to add an album, e.g. screenshots, the app crashes

**Comment by kaii-lb** [comment]
> Something is strange, your updated app is supposed to be 0.84

i totally forgot to change the app version name, oups!

> When I want to add an album, e.g. screenshots, the app crashes

i keep seeing `DIRECTORY_FUNCTIONS: java.nio.file.NoSuchFileException: /storage/emulated/0/DCIM/Cameras` in the logs, which means its not finding that path for whatever reason, but it shouldn't crash because of this.
there's also `lateinit property startForResult has not been initialized` and im currently looking into why this is happening.

thanks for the logs and help!

**Comment by DerBaliner** [comment]
> i totally forgot to change the app version name, oups!
😂😂😂

> thanks for the logs and help!
🤗👍

**Comment by kaii-lb** [comment]
i updated the release, should be fixed for both issues :D

**Comment by DerBaliner** [comment]
> i updated the release, should be fixed for both issues :D

Yup, you've fixed it 😉

Here again logs from version 0.8.5 beta
[log.txt](https://github.com/user-attachments/files/18221553/log.txt)

+ logs from Fossify Gallery, there the moving and deleting of the trash bin works, maybe it will help you to get it working in your app as well 🤷‍♂️
[2024-12-22-11-35-37.txt](https://github.com/user-attachments/files/18221556/2024-12-22-11-35-37.txt)

**Comment by kaii-lb** [comment]
> Here again logs from version 0.8.5 beta

logs for what exactly? i see the previously fixed issue there (adding albums)

**Comment by DerBaliner** [comment]
> logs for what exactly? i see the previously fixed issue there (adding albums)

Then it has served its purpose 😉

Maybe you can fix the other one too

**Comment by kaii-lb** [comment]
alright, all issues here should be fixed. can you verify so i can close this issue?

**Comment by DerBaliner** [comment]
> alright, all issues here should be fixed. can you verify so i can close this issue?

From 0.8.6 beta update

Good job you managed to fix all the problems my friend 🤗🙏👍

All previously deleted data is all visible 🫣😀
![Screenshot_20241224-235337_Photos](https://github.com/user-attachments/assets/ffac779c-1a53-4a96-84b5-c41eb19a544c)


I am happy to have been able to help 😉
