### ISSUE TITLE
Importing Albums

### ISSUE THREAD

**Issue by Disaster2life** [kaii-lb/LavenderPhotos#5]
Hey! enjoying how simple and clean it is, I just had a problem importing an album of mine that contained a comma in the name, I assume the program uses commas as separator value in importing all its albums,  Ill change my album name but I think there should be a better way of handling album names, it appears as two seperate albums in the app

**Comment by kaii-lb** [comment]
ohhh shit i never expected that xD. yes i do infact use commas as a seperator. i'll move to another implementation soon, thanks!

**Comment by kaii-lb** [comment]
Fixed! Next release will have the fix

**Comment by Disaster2life** [comment]
thank you! o/
