### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by IzzySoft** [kaii-lb/LavenderPhotos#6]
At IzzyOnDroid (where [your app is listed](https://apt.izzysoft.de/packages/com.kaii.photos)) we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). Trying for yours, I was able to successfully generate the APK using `./gradlew assembleRelease`, but the resulting APKs were not identical. Can you please let us know how you build the app, and what JDK you are using for that?

The big difference I've noticed in the diff (the full diff is > 230 kB – I can attach that here if you think it would help you) is that your build stores most `META-INF/*` and also many assets in `res/*` uncompressed or with different compression than our build, though performed from the same commit with the same configuration from your project. We've used OpenJDK 17 on Debian bookworm here – but we can also switch to OpenJDK 21 on Ubuntu jammy/noble, or even to OpenJDK 11 if needed.

We'd appreciate if you could help making your build reproducible. We've also prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Looking forward to your reply!

**Comment by kaii-lb** [comment]
hey! not sure how IzzyOnDroid works but i did not list the app myself.

as for the build method, everything is in build.sh. this is the exact java version im using:
`openjdk 17.0.10 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
OpenJDK 64-Bit Server VM (build 17.0.10+0-17.0.10b1087.21-11609105, mixed mode)`

im not doing anything else tho, so maybe its some old cached settings or something? i'll do a clean build and upload that to the same release

**Comment by IzzySoft** [comment]
> hey! not sure how IzzyOnDroid works but i did not list the app myself.

No, that needs to be done by us. But as it's FOSS, the license allows. Either someone requested to have it listed, or one of our "crawlers" suggested it.

> as for the build method

Well, JDK matches then.

> maybe its some old cached settings or something?

If you build locally from the same tree (and not from a "clean checkout" via some CI) then yes, that could be. As the "first basic rule" in our [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) state, always make the release builds from a clean tree at the commit the tag points to (so `git status` should show all is clear, and no artifacts should be there in (`.gitignore`d) places either (running `clean` before the build in Studio, or `./gradlew clean`).

> i'll do a clean build and upload that to the same release

Please don't replace what has been distributed already. You can attach an additional APK of course at releases – or simply rename it to  `*.zip` and attach it here. If you want to know beforehand if it made a difference, you can run `sha256sum` over both APKs and see if you get a different hash. The hash of the unsigned APK here was `3244f9b2dd4ab268ed0c1a3559f6483746ac3afd0c773f1e1999d92e8ec925c2` – so if your **unsigned** APK has the same hash, we found the culprit.

**Comment by kaii-lb** [comment]
> If you build locally from the same tree

i do, did the new build from a clean tree and it matches the unsigned hash you provided.

signed and uploaded that next to the old build.

**Comment by IzzySoft** [comment]
That's great news, thanks! As you already confirmed the hash, no need for me to confirm it again. But that release was already fetched here to the repo, and (except for rare cases like a broken APK or security issues) we do not replace what has already been distributed. So I wonder when the next release might be due, even if it would just be a "maintenance release" – so we can get the green shield up for your app?

**Comment by kaii-lb** [comment]
Im trying to hit a goal of weekly releases, so expect one today or next week :D

since there are no more issues on this topic, im gonna close this issue, reopen if needed

**Comment by IzzySoft** [comment]
Can you give me a ping please when the release is there? Your app is not yet integrated with any builder, we'd do that as soon as the first release was confirmed RB. Thanks!

**Comment by kaii-lb** [comment]
@IzzySoft v0.8.3-beta is up!

**Comment by IzzySoft** [comment]
And not RB, huge differences (diff is ~200 kB). Hash of the unsigned APK here is `049c32710d0ad4c4d31d6d1eb3eb92dc973bfcd5f60fa307841a67f6c3bac76d` – and the diff has not a single line not preceded by either a `-` or a `+`. Not sure if you switched the underlying system or some build options, but let me pick some examples of what is going on there now:

```diff
- -rw-r--r--  1.0 unx  4905864 bx  4905864 stor 2009-01-01 00:00:00 31ae6af2 classes.dex
+ -rw-r--r--  0.0 unx  4905864 b-  4905864 stor 1981-01-01 01:01:02 31ae6af2 classes.dex
- -rw----     1.0 fat     8324 bx     8324 stor 2009-01-01 00:00:00 9bc0fd4c res/-6.webp
+ -rw----     0.0 fat     8324 b-     8324 stor 1981-01-01 01:01:02 9bc0fd4c res/-6.webp
```

So the files are basically identical (size and hash match), but stored differently: yours are flagged `bx`, mine `b-`; so both are binaries (`b`), but yours are additionally encrypted (`x`). The `1.0` vs. `0.0` indicate a different zipfile create version (`0.0` is strange, but that's outside my expertise to interpret). Additionally, timestamps differ.

May I ask what you changed between the last build and this one?

**Comment by IzzySoft** [comment]
Just wondering: looks like you use [a non-typical way to sign your APKs](https://github.com/kaii-lb/LavenderPhotos/blob/main/build.sh#L24) with a signer I've never seen before. Our RB specialist thinks that copies the APK in a way that recompresses and changes the ZIP metadata,which could be the issue here.

Would you be open to a test on this, @kaii-lb?

* provide me an **unsigned** APK
* alongside, a copy of that signed with your tool – and another copy signed with `apksigner`
* to make sure, tell me the commit the APK was built from

I'm curious then what we find. Expectation:

* your unsigned APK and my unsigned APK will have the same sha256 checksum (i.e. will be identical)
* compared to your APK signed with `apksigner`, it will pass RB
* accordingly, your two signed ones will have different checksums – and the run against the one signed with that JAR will fail RB.

Any commit should do as a base, doesn't need to be a release. Can we do that?

**Comment by kaii-lb** [comment]
oh i didn't notice this, sorry!

actually i just noticed that i sign using signapk.jar not apksigner. [here's the builds](https://drive.google.com/drive/folders/1wcu0U-1GJC-g3C-WldWZptza5hJ7GGVK?usp=sharing)

**Comment by kaii-lb** [comment]
just made a commit to switch to apksigner :D

**Comment by IzzySoft** [comment]
Thanks! Can you give me a ping here when the next release is up, so I give the RB another try?

**Comment by kaii-lb** [comment]
ofcourse!

**Comment by IzzySoft** [comment]
Thanks!

I've no idea what causes this, but…

```diff
  -rw-r--r--  0.0 unx       56 b-       52 defN 1981-01-01 01:01:02 981abecf META-INF/com/android/build/gradle/app-metadata.properties
- -rw-r--r--  0.0 unx       46 b-       48 defN 1981-01-01 01:01:02 b8ff6554 META-INF/version-control-info.textproto
- -rw-r--r--  0.0 unx     5826 b-     5826 stor 1981-01-01 01:01:02 97337b27 assets/dexopt/baseline.prof
+ -rw-r--r--  0.0 unx      120 b-      118 defN 1981-01-01 01:01:02 e179b841 META-INF/version-control-info.textproto
+ -rw-r--r--  0.0 unx     5821 b-     5821 stor 1981-01-01 01:01:02 5e39e04b assets/dexopt/baseline.prof
  -rw-r--r--  0.0 unx      730 b-      730 stor 1981-01-01 01:01:02 1baaa0df assets/dexopt/baseline.profm
- -rw-r--r--  0.0 unx  5075108 b-  5075108 stor 1981-01-01 01:01:02 810ebe5c classes.dex
+ -rw-r--r--  0.0 unx  5075108 b-  5075108 stor 1981-01-01 01:01:02 77e607f0 classes.dex
  -rw-r--r--  0.0 unx    10096 b-    10096 stor 1981-01-01 01:01:02 9734baa0 lib/arm64-v8a/libandroidx.graphics.path.so
```

Bottom-up: your `classes.diff` has a different "ordering" than the one from my build:

```diff
 | E4.d.<init>:(LE4/f;J)V
 |: invoke-direct {v0}, Ljava/lang/Object;.<init>:()V
-|: iput-wide v2, v0, LE4/d;.a:J
 |: iput-object v1, v0, LE4/d;.b:LE4/f;
+|: iput-wide v2, v0, LE4/d;.a:J
 |: return-void
       catches       : (none)
       positions     :
@@ -39043,8 +39043,8 @@
       insns size    : 10 16-bit code units
 | E4.e.<init>:(LE4/f;Ljava/lang/Object;I)V
 |: iput v3, v0, LE4/e;.a:I
-|: iput-object v2, v0, LE4/e;.b:Ljava/lang/Object;
 |: iput-object v1, v0, LE4/e;.c:LE4/f;
+|: iput-object v2, v0, LE4/e;.b:Ljava/lang/Object;
 |: invoke-direct {v0}, Ljava/lang/Object;.<init>:()V
```

So because `classes.dex` differs, so does `baseline.prof` (as it contains the hash of the former). `META-INF/version-control-info.textproto` tells me you didn't build this from within the git repo: `generate_error_reason: NO_SUPPORTED_VCS_FOUND` – so I cannot even tell what commit that might correspond to.

Could you please build the next release from a clean tree within (a clone of) the git repo?

**Comment by kaii-lb** [comment]
interesting... i did build from a git repo tho. usually my process for releases is git clone with depth of 1 and build using a daemon-less instance of gradle

i'll try rebuilding today

**Comment by IzzySoft** [comment]
> usually my process for releases is git clone with depth of 1

Funny. Even a shallow clone should still have the `.git/` directory.

> i'll try rebuilding today

Thanks! Please do **NOT** replace the APK at the release as that has already been distributed. Be welcome to attach the APK here (rename it to `.zip` so Github allows you to attach it), and I'll see if it reproduces. If it does, you could always make a "maintenance release" to bring it out.

**Comment by kaii-lb** [comment]
> Please do **NOT** replace the APK at the releas

oh. i deleted that release as it was extremely broken, forgot to inform you guys.

new release coming up in <10 mins tho, same version number just not...cooked

**Comment by IzzySoft** [comment]
> new release coming up in <10 mins tho, same version number just not...cooked

Well, that's basically the same as replacing the APKs: v0.8.8-beta (the old one) was already pulled at IzzyOnDroid, so v0.8.8-beta (the new one) will NOT be pulled (considered as "already here"). Whoever has updated to it won't receive any update notification either.

May I suggest to NOT re-use version numbers / tag names – and rather create a NEW one? Nothing bad to retract a broken release, but letting the "fixed" one using the same name and all makes in unrecognizable that any action might be needed.

That said, I've run the new APKs through my builder, and it was not RB. Diffs are similar to those above, just the vcsInfo seems to be fixed.

Can you tell me what you build with? Which JDK, for example (we use OpenJDK-17 here, but could also switch to 21 or, if needed, 11)?

**Comment by kaii-lb** [comment]
> that's basically the same as replacing the APKs

oups? won't do that again. releasing 0.8.9 soon as i added secure folder encryption and stuff

as for jdk, i have "java-23-openjdk" installed on arch linux, i assume gradle is defaulting to that? i could try forcing JDK home to android studio's JDK 17 path and build with that if needed

**Comment by IzzySoft** [comment]
> oups?

Well… most tools remember which tags/releases they have processed by storing the tag/release name. So if you drop one that was already processed, and create a new one by the same name – it will match the stored name 🤷‍♂

> won't do that again.

Thanks 🤗

> releasing 0.8.9 soon as i added secure folder encryption and stuff

Great! Just give me a ping then and I'll check.

> as for jdk, i have "java-23-openjdk" installed on arch linux

Oof – no, that's no LTS. By default, we use OpenJDK-17. We can switch to 21 and, if needed, 11 easily, as those are also LTS. But not non-LTS versions. 21 is the currently latest LTS. Could you use that?

> i could try forcing JDK home to android studio's JDK 17 path and build with that if needed

Yes, 17 or 21 would both be fine. The non-LTS ones often add features which then are then sometimes (partially) dropped with later LTS (we had that with 18 and, IIRC also 19), so better avoid those for release builds.

**Comment by kaii-lb** [comment]
@IzzySoft check latest release, i forced JAVA_HOME to `/opt/android-studio/jbr` which has version `openjdk 17.0.10 2024-01-16`. should match now i think

**Comment by IzzySoft** [comment]
Will check. Hope the `jbr` in that path does not mean the Jetbrains SDK (which is prone to RB problems)? Hey, wow, what's that:

```json
  {
    "upstream_signed_apk_sha256": "15c5ce3044cf1e71d29aaf935aebb8dfb51d04b3d0c64a1c14de6688384dcad1",
    "built_unsigned_apk_sha256": "e2e85890c4b9c63b8852bf46605379947db9c9e1f3e0208968e820f251d1743d",
    "signature_copied_apk_sha256": "15c5ce3044cf1e71d29aaf935aebb8dfb51d04b3d0c64a1c14de6688384dcad1"
  }
```

Congrats 🥳 Hashes 1+3 match, that means it's RB! Let me finalize…

```
--- END BUILD LOG ---
Keeping '15c5ce3044cf1e71d29aaf935aebb8dfb51d04b3d0c64a1c14de6688384dcad1-com.kaii.photos-v0.8.9-beta-upstream.apk'...
Keeping 'e2e85890c4b9c63b8852bf46605379947db9c9e1f3e0208968e820f251d1743d-com.kaii.photos-v0.8.9-beta-unsigned.apk'...
Reproducible: True
```

Yeeha! So here comes your [welcome toot](https://floss.social/@IzzyOnDroid/113940072862880949):

![Image](https://github.com/user-attachments/assets/7f512647-8934-4db9-8f16-ee27949fb407)

Thanks for your patient help with this! 🤗 Mission accomplished 😃

**Comment by kaii-lb** [comment]
yay! glad all is well now

**Comment by IzzySoft** [comment]
If you indeed built with Jetbrains (as the path `/opt/android-studio/jbr` suggests), we might just have been lucky here, which is why I asked. It then might break again anytime, and we'll wonder once more…

**Comment by kaii-lb** [comment]
oh lol, i didnt notice that part. i'll check if it is and try switching to openjdk's sdk
