### ISSUE TITLE
"Data & Backup" and "Settings" button isn't clickable

### ISSUE THREAD

**Issue by CavaleriOmar** [kaii-lb/LavenderPhotos#7]
In the screenshot in the following screenshot, upon attempting to click them both the “Data & Backup” and “Settings” buttons appear dead.

Installed via F-Droid, on Android 14 (NothingOS 2.6)
![Screenshot_20241205-175658](https://github.com/user-attachments/assets/bc75ab6f-4fe2-4a64-a130-20de01a2468e)

**Comment by kaii-lb** [comment]
yes, they are non functional. the app is in beta for now.
